from .spell import Spell, SpellType
'''
法术数据来源：
1.中文wiki:https://noita.wiki.gg/zh/wiki/%E6%B3%95%E6%9C%AF
2.英文wiki:https://noita.wiki.gg/wiki/Spells
'''

SPELLS : dict[str, Spell] = {
    # 投射物(9/122)
    "spark_bolt": Spell(
        id="LIGHT_BULLET",
        name_zh="火花弹",
        type=SpellType.PROJECTILE,
        mana_drain=5,
        cast_delay=0.05,
        spread_mod=-1.0,
        critical_chance=5,
        projectile=3.0,
        explosion_radius=2,
        lifetime_min=40,
        lifetime_max=47,
        initial_speed_min=750,
        initial_speed_max=850,
        gravity=200,
        air_friction=1.7,
        mass=0.04,
        digging_strength=8,
        digging_power=400000,
        tags=["starter"],
    ),
    "spark_bolt_trigger": Spell(
        id="LIGHT_BULLET_TRIGGER",
        name_zh="触发火花弹",
        type=SpellType.PROJECTILE,
        mana_drain=10,
        cast_delay=0.05,
        critical_chance=5,
        projectile=3.0,
        explosion_radius=2,
        lifetime_min=40,
        lifetime_max=47,
        initial_speed_min=750,
        initial_speed_max=850,
        gravity=200,
        air_friction=1.7,
        mass=0.04,
        digging_strength=8,
        digging_power=400000,
        has_trigger=True,
        trigger_type="on_hit",
        trigger_capacity=1,
        tags=["trigger"],
    ),
    "magic_arrow": Spell(
        id="BULLET",
        name_zh="魔法箭",
        type=SpellType.PROJECTILE,
        mana_drain=20,
        cast_delay=0.07,
        spread_mod=2.0,
        recoil=23,
        critical_chance=5,
        projectile=10.0,
        explosion_radius=2,
        lifetime_min=40,
        lifetime_max=47,
        initial_speed_min=600,
        initial_speed_max=650,
        spread=0.6,
        gravity=200,
        air_friction=1.2,
        mass=0.07,
        tags=["pointy"],
    ),
    "magic_arrow_timer": Spell(
        id="BULLET_TIMER",
        name_zh="定时魔法箭",
        type=SpellType.PROJECTILE,
        mana_drain=35,
        cast_delay=0.07,
        spread_mod=2.0,
        recoil=23,
        critical_chance=5,
        projectile=10.0,
        explosion_radius=2,
        lifetime_min=40,
        lifetime_max=47,
        timer_Lifetime=10,
        initial_speed_min=600,
        initial_speed_max=650,
        spread=0.6,
        gravity=200,
        air_friction=1.2,
        mass=0.07,
        has_trigger=True,
        trigger_type="timer",
        trigger_capacity=1,
        tags=["timer"],
    ),
    "energy_orb": Spell(
        id="SLOW_BULLET",
        name_zh="能量球",
        type=SpellType.PROJECTILE,
        mana_drain=30,
        cast_delay=0.10,
        spread_mod=3.6,
        recoil=20,
        projectile=11.25,
        explosion=4.5,
        explosion_radius=15,
        lifetime_min=50,
        lifetime_max=57,
        initial_speed_min=180,
        initial_speed_max=240,
        spread=1.7,
        gravity=0,
        air_friction=1.0,
        mass=0.09,
        tags=["digging"],
    ),
    "bouncing_burst": Spell(
        id="RUBBER_BALL",
        name_zh="弹跳爆发",
        type=SpellType.PROJECTILE,
        mana_drain=5,
        cast_delay=-0.03,
        spread_mod=-1.0,
        projectile=3.0,
        lifetime_min=750,
        lifetime_max=757,
        initial_speed_min=650,
        initial_speed_max=750,
        dead_speed=5,
        bounces=10,
        spread=0.6,
        gravity=250,
        air_friction=0.6,
        mass=0.03,
        special_effects=["speed_damage"],
        tags=["starter"],
    ),
    "chainsaw": Spell(
        id="CHAINSAW",
        name_zh="链锯",
        type=SpellType.PROJECTILE,
        mana_drain=1,
        cast_delay=0.00,
        recharge_time_mod=-0.17,
        spread_mod=6.0,
        slice=12.75,
        explosion_radius=3,
        lifetime_min=1,
        lifetime_max=1,
        damage_every=1,
        digging_strength=10,
        digging_power=20000,
        tags=["digging"],
    ),
    "firebolt": Spell(
        id="GRENADE",
        name_zh="火焰弹",
        type=SpellType.PROJECTILE,
        uses=25,
        mana_drain=50,
        cast_delay=0.50,
        recoil=80,
        projectile=32.5,
        fire=12.5,
        explosion=47.5,
        explosion_radius=7,
        lifetime_min=493,
        lifetime_max=507,
        initial_speed_min=250,
        initial_speed_max=280,
        bounces=4,
        spread=2.9,
        gravity=0,
        air_friction=0,
        mass=0.065,
        special_effects=["fire", "frinedlyfire"],
        tags=["digging", "starter"],
    ),
    "disc_projectile": Spell(
        id="DISC_BULLET",
        name_zh="圆锯片",
        type=SpellType.PROJECTILE,
        mana_drain=20,
        cast_delay=0.17,
        speed_mod=2,
        recoil=20,
        slice=20,
        lifetime_min=743,
        lifetime_max=757,
        can_hit_time=6,
        initial_speed_min=350,
        initial_speed_max=450,
        dead_speed=5,
        bounces=2,
        spread=0.6,
        gravity=250,
        air_friction=0.6,
        mass=0.05,
        special_effects=["speeddamage", "friendlyfire"],
        tags=["sawblade"]
    ),
    # 静态投射物(0/45)
    # 投射修正(3/143)
    "damage_plus": Spell(
        id="DAMAGE",
        name_zh="伤害增强",
        type=SpellType.MODIFIER,
        mana_drain=5,
        cast_delay=0.08,
        recoil=10,
        projectile_mod=10.0,
        draw_actions=1,
    ),
    "speed_up": Spell(
        id="SPEED",
        name_zh="加速",
        type=SpellType.MODIFIER,
        mana_drain=3,
        speed_mod=2.50,
        draw_actions=1,
    ),
    "add_mana": Spell(
        id="MANA_REDUCE",
        name_zh="额外法力",
        type=SpellType.MODIFIER,
        mana_drain=-30,
        cast_delay=0.17,
        draw_actions=1,
    ),
    # 多重释放(2/14)
    "double_spell": Spell(
        id="BURST_2",
        name_zh="二重施法",
        type=SpellType.MULTICAST,
        mana_drain=0,
        multicast_count=2,
    ),
    "triple_spell": Spell(
        id="BURST_3",
        name_zh="三重施法",
        type=SpellType.MULTICAST,
        mana_drain=2,
        multicast_count=3,
    ),
    # 材料(0/26)
    # 其他(0/42)
    # 实用(0/25)
    # 被动(0/5)
}

# 按类型分组的快捷访问
_PROJECTILES = [k for k, v in SPELLS.items() if v.type == SpellType.PROJECTILE]
_STATIC_PROJECTILES = [k for k, v in SPELLS.items() if v.type == SpellType.STATIC_PROJECTILE]
_MODIFIERS  = [k for k, v in SPELLS.items() if v.type == SpellType.MODIFIER]
_MULTICASTS = [k for k, v in SPELLS.items() if v.type == SpellType.MULTICAST]
_MATERIALS = [k for k, v in SPELLS.items() if v.type == SpellType.MATERIAL]
_OTHERS = [k for k, v in SPELLS.items() if v.type == SpellType.OTHER]
_UTILITIES = [k for k, v in SPELLS.items() if v.type == SpellType.UTILITY]
_PASSIVES = [k for k, v in SPELLS.items() if v.type == SpellType.PASSIVE]

ALL_SPELL_IDS = list(SPELLS.keys())
BUILDABLE_IDS = _PROJECTILES + _STATIC_PROJECTILES + _MODIFIERS + _MULTICASTS + _MATERIALS + _OTHERS + _UTILITIES + _PASSIVES